### ISSUE TITLE
Implement purge function

### ISSUE THREAD

**Issue by muhrin** [muhrin/mincepy#11]
As the size of a database grows it may be useful to have a `purge` capability that deletes or compresses items in the history that no longer have any references to them.  It may be further useful to have this be able to be restricted to items that are older than a certain threshold.

This could be included as a `mince purge`

**Comment by atygesen** [comment]
Just noting, that you already have `minki purge`, so the naming is rather close.

**Comment by muhrin** [comment]
Yes, I think that's fine (and possibly an advantage).  After all they're both namedpaced with their repsective names so the context is clear and the character of the operation is similar.  What's more, as far as `mincepy` is concerned, `minkipy` doesn't even exist (in the sense that the former can, and hopefully will, be used with no intention of using the latter).

**Comment by muhrin** [comment]
Make sure to add a `--dry-run` to be able to verify what would happen first (without making modifications).

**Comment by muhrin** [comment]
This is now possible in v0.15.24 using the `mince purge` cli command or `historian.purge()` programmatically.
